### ISSUE TITLE
Set Hotkeys

### ISSUE THREAD

**Issue by markjamesm** [markjamesm/MusicSharp#18]
Need to set menu hotkeys so that users can navigate through the app using shortcut keys. The hotkeys themselves are easy enough to implement through Terminal.Gui, but some thought needs to go into which hotkeys are used and for what function. So far, we need hotkeys for:

- Open audio file
- Open stream
- About menu
- Playlist window focus
- Track window focus
- Play button
- Stop button
- Pause button
- Volume up
- Volume down

Upcoming sections include:

- Open playlist
- Save playlist to file
- Add tracks to playlist

**Comment by ramonB1996** [comment]
Hi MarkJames,

I would love to contribute to this library every once in a while. I found it because of your reference in the C# digest newsletter a while back. 

I have some experience with Xamarin Development in C#, so hopefully this should not be too hard.
Is it okay if I try to make a PR for this?

Kind regards,

Ramon

**Comment by ramonB1996** [comment]
I see that you have implemented hotkeys already, should this issue be closed? 
If not, what is missing?

**Comment by markjamesm** [comment]
> I see that you have implemented hotkeys already, should this issue be closed?
> If not, what is missing?

I had forgotten to close this issue after the hotkeys were implemented, my apologies! 

I haven't had as much time as I'd like recently to work on the project, and so PRs would be much appreciated! If there's any other issues you're interested in looking at, feel free to open a PR.

**Comment by ramonB1996** [comment]
No problem! Thank you for letting me contribute!

I read that you are starting a new study in your blog, good luck!

A question out of curiosity: Do you have a goal that you would like to achieve with this Repository?

**Comment by markjamesm** [comment]
Thanks!

My main goal is to implement cross platform support and then continue working on features (seek buttons, support for saving playlists). 

I was experimenting recently in the [cross-platform ](https://github.com/markjamesm/MusicSharp/tree/cross-platform) branch using the [SharpAudio library](https://github.com/feliwir/SharpAudio) but ran into some difficulties. I was able to get the library working on Windows, but haven't yet had luck on Mac or Linux. I haven't yet found a decent cross-platform audio library which works in .NET Core.
