### ISSUE TITLE
Merge the play and pause buttons

### ISSUE THREAD

**Issue by marijnz0r** [markjamesm/MusicSharp#21]
It feels very natural for the play and pause buttons to be inverse. I think it's a cool idea to merge the play and pause buttons to one button. So if you're playing something, pause it, if you're paused, resume playing.

**Comment by markjamesm** [comment]
I think this could be neat! It would also simplify the UI by having one less button.

**Comment by markjamesm** [comment]
PR https://github.com/markjamesm/MusicSharp/pull/22 implemented this functionality, so closing this issue.

Thanks marijnz0r!
