### ISSUE TITLE
Pressing enter when not having valid file selected and having no previous valid file selected causes crash

### ISSUE THREAD

**Issue by DomDom3333** [markjamesm/MusicSharp#26]
Steps to Recreate:

Ensure no Valid file has previously selected
Open Application
Press F1 to Open File
Select Path (Or otherwise no valid File)
Press Enter
Crash

Possible Solutions:

Check if File is valid inside OpenFile(string path) in WinPlayer.cs Line 39
Check if LastFileOpened is empty/exists before telling it to open it at Tui.cs Line 214

Ideally both should probably be added.

**Comment by markjamesm** [comment]
Many thanks for catching this! I entered an invalid file (C:\test.exe) into the open file dialog and the app crashed with the following exception in WinPlayer.cs line 41

![Winplayer error message](https://user-images.githubusercontent.com/20845425/99097277-62105080-25a5-11eb-917c-e0daf53fb4c0.png)

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=The system cannot find the file specified. (0x80070002)
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

**Comment by markjamesm** [comment]
This issue has now been solved as of PR #29
