### ISSUE TITLE
Have the Audio File Open Dialog Filter by Filetype

### ISSUE THREAD

**Issue by markjamesm** [markjamesm/MusicSharp#9]
Line 164 of the [Gui Class](https://github.com/markjamesm/MusicSharp/blob/main/src/view/Gui.cs) opens a new file open dialog and passes the FilePath it outputs as a string to the audio player to load. Need to determine whether or not it is possible to have this file dialog filter based on file extension. For example, .exe files should always be omitted since they aren't audio files.

Here's how the intended behavior should function (note the lack of other filetypes in the folder):

![MusicSharp-open-dialog](https://user-images.githubusercontent.com/20845425/97772379-d74b4280-1b1c-11eb-9163-2705583c49fa.png)

**Comment by rishi-shah** [comment]
I think we can close this issue :)

**Comment by markjamesm** [comment]
> I think we can close this issue :)

Agreed! Many thanks for taking care of this issue. 👍
